remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: emesbi
author: emesbi
description: blog for msb
show_downloads: false
github:
  owner_url: https://github.com/hydezeke
logo: /docs/assets/images/avatar.jpg