theme: minima
minima:
  skin: solarized
title: emesbi
author: emesbi
description: blog for msb
show_downloads: false
github:
  owner_url: https://github.com/hydezeke
logo: /docs/assets/images/avatar.jpg